---
- hosts: glusto_hosts
  gather_facts: no
  remote_user: root

  tasks:
  -  name: Add EPEL repository
     yum_repository:
       name: epel
       description: EPEL YUM repo
       mirrorlist: https://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=$basearch

  - name: Install required packages
    yum:
      name: ['git', 'yum-plugin-copr','python-pip','gcc','python-devel']
      state: latest

  - name: Install EPEL required packages
    yum:
      name: "python-pip"
      state: present

  - name: upgrade setuptools
    pip:
      name: ['setuptools','six']
      extra_args: --upgrade

  - name: enable copr repo
    shell: yum copr enable sac/gdeploy -y

  - name: install gdeploy
    yum:
      name: gdeploy
      state: latest

  - name: Install Glusto
    pip: name=' git+git://github.com/loadtheaccumulator/glusto.git' editable=false

  - name: Clone the glusto-tests repo.
    git:
        repo: git://review.gluster.org/glusto-tests.git
        dest: /root/glusto-tests

  - name: Install glustolibs
    command: "python setup.py develop chdir=/root/glusto-tests/{{item}}"
    with_items:
    - glustolibs-gluster
    - glustolibs-io
    - glustolibs-misc
